<?php

/**
 * PluginPosRentHouseCrawlPos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPosRentHouseCrawlPos extends BasePosRentHouseCrawlPos
{
    public function checkCid(){
        return $this->getTable()->checkCid($this->cid);
    }
    public function getSource(){
        return Doctrine::getTable('PosRentHouseCrawlSource')->createQuery()
                ->where('id = ?',$this->getSourceId())
                ->fetchOne();
    }
    public function getListSamePos(){
        $query = Doctrine::getTable('PosRentHouse')->createQuery();
        if($this->contact_tel){
            $query = $query->orWhere('contact_tel like ?','%'.$this->contact_tel.'%');
        }
        if($this->contact_email){
            $query = $query->orWhere('contact_email like ?','%'.$this->contact_email.'%');
        }
        return $samepos;
    }
}