<?php

/**
 * PluginPosEventComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPosEventComment extends BasePosEventComment
{
    public function getCountComment($eventId){
      $q = $this->createQuery()
        ->where('pos_event_id =?',$eventId)
        ->andWhere('status =?',1)
        ->orderBy('created_at DESC');
      return $q->count();
    }

}