<?php

/**
 * PluginPosSponsorTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPosSponsorTable extends Doctrine_Table {
/**
 * Returns an instance of this class.
 *
 * @return object PluginPosSponsorTable
 */
    public static function getInstance() {
        return Doctrine_Core::getTable('PluginPosSponsor');
    }
    public function getSponsorPos($num=null) {
        return $this->createQuery('p')
        ->where('p.expire_date > ?', date( 'Y-m-d h:i:s', time() ))
        ->orderBy('p.sort_order DESC')
        ->limit($num)
        ->execute();
    }
}