<?php

/**
 * PluginPosGoogleFlowContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPosGoogleFlowContentTable extends Doctrine_Table
{
    const init = 0; // da khoi tao
    const inprocess = 1; // dang chay
    const finish = 2; // da xong
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPosGoogleFlowContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPosGoogleFlowContent');
    }
    public function getListGoogleFlowContent($page = 1, $size = 10){
        $q = $this->createQuery('p')
            ->where('p.status = ?', self::init);
        return $this->getPager($q, $page, $size);
    }
    protected function getPager(Doctrine_Query $q, $page, $size) {
        $pager = new sfDoctrinePager('PosGoogleFlowContent', $size);
        $pager->setQuery($q);
        $pager->setPage($page);
        return $pager;
    }
    public function retrieveByFlowId($flow_id){
        $q = $this->createQuery()
            ->where('flow_id = ?',$flow_id)
            ->andWhere('status = ?',self::init);
        return $q->execute();
    }
    public function retrievePagerByFlowId($flow_id,$page=1,$size = 100){
        $q = $this->createQuery()
            ->where('flow_id = ?',$flow_id)
            ->andWhere('status = ?',self::init);
        $pager = $this->getPager($q, $page, $size);
        $pager->init();
        return $pager->getResults();
    }
}