<?php

/**
 * PluginPosGoogleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPosGoogleTable extends Doctrine_Table
{
    const pos_init = 0; // chua dung
    const pos_is_set = 1; // da dung
    const pos_is_image = 2; // da lay them content image
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPosGoogleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPosGoogle');
    }
    public function getListGooglePos($page = 1, $size = 10, $flow_id = 0){
        $q = $this->createQuery()
            ->where('status = ?',self::pos_init);
        if($flow_id)
            $q = $q->andWhere('flow_id = ?',$flow_id);
        $pager = $this->getPager($q, $page, $size);
        $pager->init();
        return $pager->getResults();
    }
    public function getListGooglePosPager($page = 1, $size = 10, $flow_id = 0){
        $q = $this->createQuery()
            ->where('status = ?',self::pos_init);
        if($flow_id)
            $q = $q->andWhere('flow_id = ?',$flow_id);
        return $this->getPager($q, $page, $size);
    }
    protected function getPager(Doctrine_Query $q, $page, $size) {
        $pager = new sfDoctrinePager('Pos', $size);
        $pager->setQuery($q);
        $pager->setPage($page);
        return $pager;
    }
    public function checkCID($cid=''){
        $q = $this->createQuery()
            ->where('cid = ?',$cid);
        if($q->count()){
            return true;
        }else{
            return false;
        }
    }
}