<?php

/**
 * PluginPosEventPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPosEventPhotoTable extends Doctrine_Table
{
    const is_public = 1;
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPosEventPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPosEventPhoto');
    }
    public function getListImagesOfPosEvent($id,$limit = 4){
        $q = $this->createQuery()
          ->where('pos_event_id =?',$id)
          ->andWhere('is_public =?',self::is_public)
          ->orderBy('created_at DESC')
          ->limit($limit);
        return $q->execute();
    }
    public function save($memberId,$eventId,$fileId,$status = 1,$isPublic = 1) {
        $eventPhoto = new PosEventPhoto();
        $eventPhoto->member_id = $memberId;
        $eventPhoto->pos_event_id = $eventId;
        $eventPhoto->file_id = $fileId;
        $eventPhoto->status = $status;
        $eventPhoto->is_public = $isPublic;
        $eventPhoto->save();
        return $eventPhoto;
    }
}