<?php

/**
 * PluginPosGoogleAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPosGoogleAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPosGoogleAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPosGoogleArea');
    }
    public function getListGoogleArea($page = 1, $size = 10){
        $q = $this->createQuery()
            ->groupBy('area');
        return $q->execute();
    }
    protected function getPager(Doctrine_Query $q, $page, $size) {
        $pager = new sfDoctrinePager('PosGoogleArea', $size);
        $pager->setQuery($q);
        $pager->setPage($page);
        return $pager;
    }
    public function retrieveByAreaAndStop($area = "",$page = 0,$size=10){
        $q = $this->createQuery()
            ->where('area = ?',$area)
//            ->andWhere('id > ?',$stop)
            ->orderBy('id ASC');
//            ->limit($size);
        $pager = $this->getPager($q, $page, $size);
        $pager->init();
        return $pager->getResults();
    }
}