<?php

/**
 * BasePosCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $name_table
 * @property string $code
 * @property integer $parent_id
 * @property integer $type
 * @property integer $file_id
 * @property integer $order
 * @property string $detail_name
 * @property integer $view_flag
 * @property PosCategory $PosCategory
 * @property File $File
 * @property Doctrine_Collection $Pos
 * @property Doctrine_Collection $PosCheckin
 * @property Doctrine_Collection $PosComment
 * @property Doctrine_Collection $PosFollow
 * @property Doctrine_Collection $PosPhoto
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getNameTable()   Returns the current record's "name_table" value
 * @method string              getCode()        Returns the current record's "code" value
 * @method integer             getParentId()    Returns the current record's "parent_id" value
 * @method integer             getType()        Returns the current record's "type" value
 * @method integer             getFileId()      Returns the current record's "file_id" value
 * @method integer             getOrder()       Returns the current record's "order" value
 * @method string              getDetailName()  Returns the current record's "detail_name" value
 * @method integer             getViewFlag()    Returns the current record's "view_flag" value
 * @method PosCategory         getPosCategory() Returns the current record's "PosCategory" value
 * @method File                getFile()        Returns the current record's "File" value
 * @method Doctrine_Collection getPos()         Returns the current record's "Pos" collection
 * @method Doctrine_Collection getPosCheckin()  Returns the current record's "PosCheckin" collection
 * @method Doctrine_Collection getPosComment()  Returns the current record's "PosComment" collection
 * @method Doctrine_Collection getPosFollow()   Returns the current record's "PosFollow" collection
 * @method Doctrine_Collection getPosPhoto()    Returns the current record's "PosPhoto" collection
 * @method PosCategory         setId()          Sets the current record's "id" value
 * @method PosCategory         setName()        Sets the current record's "name" value
 * @method PosCategory         setDescription() Sets the current record's "description" value
 * @method PosCategory         setNameTable()   Sets the current record's "name_table" value
 * @method PosCategory         setCode()        Sets the current record's "code" value
 * @method PosCategory         setParentId()    Sets the current record's "parent_id" value
 * @method PosCategory         setType()        Sets the current record's "type" value
 * @method PosCategory         setFileId()      Sets the current record's "file_id" value
 * @method PosCategory         setOrder()       Sets the current record's "order" value
 * @method PosCategory         setDetailName()  Sets the current record's "detail_name" value
 * @method PosCategory         setViewFlag()    Sets the current record's "view_flag" value
 * @method PosCategory         setPosCategory() Sets the current record's "PosCategory" value
 * @method PosCategory         setFile()        Sets the current record's "File" value
 * @method PosCategory         setPos()         Sets the current record's "Pos" collection
 * @method PosCategory         setPosCheckin()  Sets the current record's "PosCheckin" collection
 * @method PosCategory         setPosComment()  Sets the current record's "PosComment" collection
 * @method PosCategory         setPosFollow()   Sets the current record's "PosFollow" collection
 * @method PosCategory         setPosPhoto()    Sets the current record's "PosPhoto" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosCategory extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies category',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'name is of category',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'comment' => 'desc is of category',
             ));
        $this->hasColumn('name_table', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tên bảng thuộc tính tương ứng với Category',
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'comment' => 'code of pos category',
             'length' => 100,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'id identifies category',
             'length' => 4,
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'comment' => '',
             'length' => 1,
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'File id',
             'length' => 4,
             ));
        $this->hasColumn('order', 'integer', 1, array(
             'type' => 'integer',
             'default' => 10,
             'comment' => 'File id',
             'length' => 1,
             ));
        $this->hasColumn('detail_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'sub name is of category',
             'length' => 255,
             ));
        $this->hasColumn('view_flag', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'comment' => 'File id',
             'length' => 1,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PosCategory', array(
             'local' => 'parent_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('Pos', array(
             'local' => 'id',
             'foreign' => 'pos_category_id'));

        $this->hasMany('PosCheckin', array(
             'local' => 'id',
             'foreign' => 'pos_category_id'));

        $this->hasMany('PosComment', array(
             'local' => 'id',
             'foreign' => 'pos_category_id'));

        $this->hasMany('PosFollow', array(
             'local' => 'id',
             'foreign' => 'pos_category_id'));

        $this->hasMany('PosPhoto', array(
             'local' => 'id',
             'foreign' => 'pos_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}