<?php

/**
 * BasePosLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pos_id
 * @property integer $member_id
 * @property integer $object_id
 * @property varchar $action_name
 * @property integer $is_public
 * @property Pos $Pos
 * @property Member $Member
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method integer getPosId()       Returns the current record's "pos_id" value
 * @method integer getMemberId()    Returns the current record's "member_id" value
 * @method integer getObjectId()    Returns the current record's "object_id" value
 * @method varchar getActionName()  Returns the current record's "action_name" value
 * @method integer getIsPublic()    Returns the current record's "is_public" value
 * @method Pos     getPos()         Returns the current record's "Pos" value
 * @method Member  getMember()      Returns the current record's "Member" value
 * @method PosLog  setId()          Sets the current record's "id" value
 * @method PosLog  setPosId()       Sets the current record's "pos_id" value
 * @method PosLog  setMemberId()    Sets the current record's "member_id" value
 * @method PosLog  setObjectId()    Sets the current record's "object_id" value
 * @method PosLog  setActionName()  Sets the current record's "action_name" value
 * @method PosLog  setIsPublic()    Sets the current record's "is_public" value
 * @method PosLog  setPos()         Sets the current record's "Pos" value
 * @method PosLog  setMember()      Sets the current record's "Member" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosLog extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_log');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies pos_log',
             'length' => 4,
             ));
        $this->hasColumn('pos_id', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'id identifies pos',
             'length' => 4,
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id is of poster',
             'length' => 4,
             ));
        $this->hasColumn('object_id', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'id của tác động',
             'length' => 4,
             ));
        $this->hasColumn('action_name', 'varchar', 100, array(
             'type' => 'varchar',
             'comment' => 'tên các tác động lên địa điểm',
             'length' => 100,
             ));
        $this->hasColumn('is_public', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '1',
             'comment' => '',
             'length' => 1,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pos', array(
             'local' => 'pos_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}