<?php

/**
 * BasePosRentHouseCrawlSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $area
 * @property string $source
 * @property string $url
 * @property integer $status
 * 
 * @method integer                 getId()     Returns the current record's "id" value
 * @method string                  getArea()   Returns the current record's "area" value
 * @method string                  getSource() Returns the current record's "source" value
 * @method string                  getUrl()    Returns the current record's "url" value
 * @method integer                 getStatus() Returns the current record's "status" value
 * @method PosRentHouseCrawlSource setId()     Sets the current record's "id" value
 * @method PosRentHouseCrawlSource setArea()   Sets the current record's "area" value
 * @method PosRentHouseCrawlSource setSource() Sets the current record's "source" value
 * @method PosRentHouseCrawlSource setUrl()    Sets the current record's "url" value
 * @method PosRentHouseCrawlSource setStatus() Sets the current record's "status" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosRentHouseCrawlSource extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_rent_house_crawl_source');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies pos',
             'length' => 4,
             ));
        $this->hasColumn('area', 'string', 50, array(
             'type' => 'string',
             'comment' => 'id identifies category',
             'length' => 50,
             ));
        $this->hasColumn('source', 'string', 50, array(
             'type' => 'string',
             'comment' => 'id identifies category',
             'length' => 50,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'comment' => 'url lay thong tin',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'trang thai of dia diem',
             'length' => 2,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}