<?php

/**
 * BasePosWarn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pos_id
 * @property integer $member_id
 * @property string $content
 * @property Pos $Pos
 * @property Member $Member
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method integer getPosId()     Returns the current record's "pos_id" value
 * @method integer getMemberId()  Returns the current record's "member_id" value
 * @method string  getContent()   Returns the current record's "content" value
 * @method Pos     getPos()       Returns the current record's "Pos" value
 * @method Member  getMember()    Returns the current record's "Member" value
 * @method PosWarn setId()        Sets the current record's "id" value
 * @method PosWarn setPosId()     Sets the current record's "pos_id" value
 * @method PosWarn setMemberId()  Sets the current record's "member_id" value
 * @method PosWarn setContent()   Sets the current record's "content" value
 * @method PosWarn setPos()       Sets the current record's "Pos" value
 * @method PosWarn setMember()    Sets the current record's "Member" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosWarn extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_warn');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies pos_warn',
             'length' => 4,
             ));
        $this->hasColumn('pos_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id identifies pos',
             'length' => 4,
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id is of poster',
             'length' => 4,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'content is of pos_warn',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pos', array(
             'local' => 'pos_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}