<?php

/**
 * BasePosGoogle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $cid
 * @property string $title
 * @property string $description
 * @property string $address
 * @property string $tel
 * @property string $website
 * @property double $lat
 * @property double $lng
 * @property string $tags
 * @property string $place_url
 * @property string $image_url
 * @property string $category
 * @property integer $status
 * @property string $keyword
 * @property string $url_search
 * @property text $content
 * @property integer $flow_id
 * @property PosGoogleFlow $PosGoogleFlow
 * 
 * @method integer       getId()            Returns the current record's "id" value
 * @method string        getCid()           Returns the current record's "cid" value
 * @method string        getTitle()         Returns the current record's "title" value
 * @method string        getDescription()   Returns the current record's "description" value
 * @method string        getAddress()       Returns the current record's "address" value
 * @method string        getTel()           Returns the current record's "tel" value
 * @method string        getWebsite()       Returns the current record's "website" value
 * @method double        getLat()           Returns the current record's "lat" value
 * @method double        getLng()           Returns the current record's "lng" value
 * @method string        getTags()          Returns the current record's "tags" value
 * @method string        getPlaceUrl()      Returns the current record's "place_url" value
 * @method string        getImageUrl()      Returns the current record's "image_url" value
 * @method string        getCategory()      Returns the current record's "category" value
 * @method integer       getStatus()        Returns the current record's "status" value
 * @method string        getKeyword()       Returns the current record's "keyword" value
 * @method string        getUrlSearch()     Returns the current record's "url_search" value
 * @method text          getContent()       Returns the current record's "content" value
 * @method integer       getFlowId()        Returns the current record's "flow_id" value
 * @method PosGoogleFlow getPosGoogleFlow() Returns the current record's "PosGoogleFlow" value
 * @method PosGoogle     setId()            Sets the current record's "id" value
 * @method PosGoogle     setCid()           Sets the current record's "cid" value
 * @method PosGoogle     setTitle()         Sets the current record's "title" value
 * @method PosGoogle     setDescription()   Sets the current record's "description" value
 * @method PosGoogle     setAddress()       Sets the current record's "address" value
 * @method PosGoogle     setTel()           Sets the current record's "tel" value
 * @method PosGoogle     setWebsite()       Sets the current record's "website" value
 * @method PosGoogle     setLat()           Sets the current record's "lat" value
 * @method PosGoogle     setLng()           Sets the current record's "lng" value
 * @method PosGoogle     setTags()          Sets the current record's "tags" value
 * @method PosGoogle     setPlaceUrl()      Sets the current record's "place_url" value
 * @method PosGoogle     setImageUrl()      Sets the current record's "image_url" value
 * @method PosGoogle     setCategory()      Sets the current record's "category" value
 * @method PosGoogle     setStatus()        Sets the current record's "status" value
 * @method PosGoogle     setKeyword()       Sets the current record's "keyword" value
 * @method PosGoogle     setUrlSearch()     Sets the current record's "url_search" value
 * @method PosGoogle     setContent()       Sets the current record's "content" value
 * @method PosGoogle     setFlowId()        Sets the current record's "flow_id" value
 * @method PosGoogle     setPosGoogleFlow() Sets the current record's "PosGoogleFlow" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosGoogle extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_google');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies pos',
             'length' => 4,
             ));
        $this->hasColumn('cid', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'id of pos google',
             'length' => 25,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'title is of pos',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'comment' => 'desc is of pos',
             ));
        $this->hasColumn('address', 'string', null, array(
             'type' => 'string',
             'comment' => 'address is of pos',
             ));
        $this->hasColumn('tel', 'string', 20, array(
             'type' => 'string',
             'comment' => 'tel is of pos',
             'length' => 20,
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'comment' => 'website is of pos',
             'length' => 255,
             ));
        $this->hasColumn('lat', 'double', null, array(
             'type' => 'double',
             'comment' => 'latitude theo google map',
             'length' => '',
             ));
        $this->hasColumn('lng', 'double', null, array(
             'type' => 'double',
             'comment' => 'longitude theo google map',
             'length' => '',
             ));
        $this->hasColumn('tags', 'string', 255, array(
             'type' => 'string',
             'comment' => 'tags is of pos',
             'length' => 255,
             ));
        $this->hasColumn('place_url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Place url',
             'length' => 255,
             ));
        $this->hasColumn('image_url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'File image url',
             'length' => 255,
             ));
        $this->hasColumn('category', 'string', 255, array(
             'type' => 'string',
             'comment' => 'id identifies category',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'trang thai xu ly of dia diem',
             'length' => 2,
             ));
        $this->hasColumn('keyword', 'string', 50, array(
             'type' => 'string',
             'comment' => 'id identifies category',
             'length' => 50,
             ));
        $this->hasColumn('url_search', 'string', 255, array(
             'type' => 'string',
             'comment' => 'url lay thong tin',
             'length' => 255,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             'comment' => 'File url',
             ));
        $this->hasColumn('flow_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id identifies pos',
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PosGoogleFlow', array(
             'local' => 'flow_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}