<?php

/**
 * BasePosRentHouseCrawlPos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $source_id
 * @property string $cid
 * @property string $url
 * @property string $title
 * @property string $description
 * @property string $address
 * @property string $tel
 * @property string $website
 * @property float $lat
 * @property float $lng
 * @property string $tags
 * @property integer $file_id
 * @property integer $pos_sub_category_id
 * @property string $price
 * @property string $unit_price
 * @property string $area
 * @property string $unit_area
 * @property integer $num_room
 * @property string $direction
 * @property string $contact_name
 * @property string $contact_email
 * @property string $contact_tel
 * @property integer $status
 * 
 * @method integer              getId()                  Returns the current record's "id" value
 * @method integer              getSourceId()            Returns the current record's "source_id" value
 * @method string               getCid()                 Returns the current record's "cid" value
 * @method string               getUrl()                 Returns the current record's "url" value
 * @method string               getTitle()               Returns the current record's "title" value
 * @method string               getDescription()         Returns the current record's "description" value
 * @method string               getAddress()             Returns the current record's "address" value
 * @method string               getTel()                 Returns the current record's "tel" value
 * @method string               getWebsite()             Returns the current record's "website" value
 * @method float                getLat()                 Returns the current record's "lat" value
 * @method float                getLng()                 Returns the current record's "lng" value
 * @method string               getTags()                Returns the current record's "tags" value
 * @method integer              getFileId()              Returns the current record's "file_id" value
 * @method integer              getPosSubCategoryId()    Returns the current record's "pos_sub_category_id" value
 * @method string               getPrice()               Returns the current record's "price" value
 * @method string               getUnitPrice()           Returns the current record's "unit_price" value
 * @method string               getArea()                Returns the current record's "area" value
 * @method string               getUnitArea()            Returns the current record's "unit_area" value
 * @method integer              getNumRoom()             Returns the current record's "num_room" value
 * @method string               getDirection()           Returns the current record's "direction" value
 * @method string               getContactName()         Returns the current record's "contact_name" value
 * @method string               getContactEmail()        Returns the current record's "contact_email" value
 * @method string               getContactTel()          Returns the current record's "contact_tel" value
 * @method integer              getStatus()              Returns the current record's "status" value
 * @method PosRentHouseCrawlPos setId()                  Sets the current record's "id" value
 * @method PosRentHouseCrawlPos setSourceId()            Sets the current record's "source_id" value
 * @method PosRentHouseCrawlPos setCid()                 Sets the current record's "cid" value
 * @method PosRentHouseCrawlPos setUrl()                 Sets the current record's "url" value
 * @method PosRentHouseCrawlPos setTitle()               Sets the current record's "title" value
 * @method PosRentHouseCrawlPos setDescription()         Sets the current record's "description" value
 * @method PosRentHouseCrawlPos setAddress()             Sets the current record's "address" value
 * @method PosRentHouseCrawlPos setTel()                 Sets the current record's "tel" value
 * @method PosRentHouseCrawlPos setWebsite()             Sets the current record's "website" value
 * @method PosRentHouseCrawlPos setLat()                 Sets the current record's "lat" value
 * @method PosRentHouseCrawlPos setLng()                 Sets the current record's "lng" value
 * @method PosRentHouseCrawlPos setTags()                Sets the current record's "tags" value
 * @method PosRentHouseCrawlPos setFileId()              Sets the current record's "file_id" value
 * @method PosRentHouseCrawlPos setPosSubCategoryId()    Sets the current record's "pos_sub_category_id" value
 * @method PosRentHouseCrawlPos setPrice()               Sets the current record's "price" value
 * @method PosRentHouseCrawlPos setUnitPrice()           Sets the current record's "unit_price" value
 * @method PosRentHouseCrawlPos setArea()                Sets the current record's "area" value
 * @method PosRentHouseCrawlPos setUnitArea()            Sets the current record's "unit_area" value
 * @method PosRentHouseCrawlPos setNumRoom()             Sets the current record's "num_room" value
 * @method PosRentHouseCrawlPos setDirection()           Sets the current record's "direction" value
 * @method PosRentHouseCrawlPos setContactName()         Sets the current record's "contact_name" value
 * @method PosRentHouseCrawlPos setContactEmail()        Sets the current record's "contact_email" value
 * @method PosRentHouseCrawlPos setContactTel()          Sets the current record's "contact_tel" value
 * @method PosRentHouseCrawlPos setStatus()              Sets the current record's "status" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosRentHouseCrawlPos extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_rent_house_crawl_pos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies pos',
             'length' => 4,
             ));
        $this->hasColumn('source_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id is of poster',
             'length' => 4,
             ));
        $this->hasColumn('cid', 'string', 50, array(
             'type' => 'string',
             'comment' => 'url lay thong tin',
             'length' => 50,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'comment' => 'url lay thong tin',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'title is of pos',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'comment' => 'desc is of pos',
             ));
        $this->hasColumn('address', 'string', null, array(
             'type' => 'string',
             'comment' => 'address is of pos',
             ));
        $this->hasColumn('tel', 'string', 20, array(
             'type' => 'string',
             'comment' => 'tel is of pos',
             'length' => 20,
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'comment' => 'website is of pos',
             'length' => 255,
             ));
        $this->hasColumn('lat', 'float', null, array(
             'type' => 'float',
             'comment' => 'latitude theo google map',
             'length' => '',
             ));
        $this->hasColumn('lng', 'float', null, array(
             'type' => 'float',
             'comment' => 'longitude theo google map',
             'length' => '',
             ));
        $this->hasColumn('tags', 'string', 255, array(
             'type' => 'string',
             'comment' => 'tags is of pos',
             'length' => 255,
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'File id',
             'length' => 4,
             ));
        $this->hasColumn('pos_sub_category_id', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'id identifies sub_category',
             'length' => 4,
             ));
        $this->hasColumn('price', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Giá cho thuê nhà',
             'length' => 50,
             ));
        $this->hasColumn('unit_price', 'string', 100, array(
             'type' => 'string',
             'comment' => 'đơn vị giá',
             'length' => 100,
             ));
        $this->hasColumn('area', 'string', 50, array(
             'type' => 'string',
             'comment' => 'diện tích phòng ',
             'length' => 50,
             ));
        $this->hasColumn('unit_area', 'string', 100, array(
             'type' => 'string',
             'comment' => 'đơn vị diện tích',
             'length' => 100,
             ));
        $this->hasColumn('num_room', 'integer', 1, array(
             'type' => 'integer',
             'comment' => 'Số phòng ',
             'length' => 1,
             ));
        $this->hasColumn('direction', 'string', 100, array(
             'type' => 'string',
             'comment' => 'hướng nhà ',
             'length' => 100,
             ));
        $this->hasColumn('contact_name', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Tên người liên hệ',
             'length' => 50,
             ));
        $this->hasColumn('contact_email', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Email liên hệ',
             'length' => 50,
             ));
        $this->hasColumn('contact_tel', 'string', 20, array(
             'type' => 'string',
             'comment' => 'Điện thoại liên hệ',
             'length' => 20,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'trang thai of dia diem',
             'length' => 2,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}