<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PosEvent', 'doctrine');

/**
 * BasePosEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pos_id
 * @property float $lat
 * @property float $lng
 * @property integer $member_id
 * @property integer $pos_event_category_id
 * @property string $title
 * @property string $description
 * @property string $website
 * @property integer $file_id
 * @property timestamp $start_time
 * @property timestamp $end_time
 * @property integer $is_public
 * @property string $meta
 * @property integer $del_flag
 * @property integer $rank
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Pos $Pos
 * @property Member $Member
 * @property File $File
 * @property PosEventCategory $PosEventCategory
 * @property Doctrine_Collection $PosEventPhoto
 * @property Doctrine_Collection $PosEventFollow
 * @property Doctrine_Collection $PosEventCheckin
 * @property Doctrine_Collection $PosEventComment
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getPosId()                 Returns the current record's "pos_id" value
 * @method float               getLat()                   Returns the current record's "lat" value
 * @method float               getLng()                   Returns the current record's "lng" value
 * @method integer             getMemberId()              Returns the current record's "member_id" value
 * @method integer             getPosEventCategoryId()    Returns the current record's "pos_event_category_id" value
 * @method string              getTitle()                 Returns the current record's "title" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method string              getWebsite()               Returns the current record's "website" value
 * @method integer             getFileId()                Returns the current record's "file_id" value
 * @method timestamp           getStartTime()             Returns the current record's "start_time" value
 * @method timestamp           getEndTime()               Returns the current record's "end_time" value
 * @method integer             getIsPublic()              Returns the current record's "is_public" value
 * @method string              getMeta()                  Returns the current record's "meta" value
 * @method integer             getDelFlag()               Returns the current record's "del_flag" value
 * @method integer             getRank()                  Returns the current record's "rank" value
 * @method timestamp           getCreatedAt()             Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()             Returns the current record's "updated_at" value
 * @method Pos                 getPos()                   Returns the current record's "Pos" value
 * @method Member              getMember()                Returns the current record's "Member" value
 * @method File                getFile()                  Returns the current record's "File" value
 * @method PosEventCategory    getPosEventCategory()      Returns the current record's "PosEventCategory" value
 * @method Doctrine_Collection getPosEventPhoto()         Returns the current record's "PosEventPhoto" collection
 * @method Doctrine_Collection getPosEventFollow()        Returns the current record's "PosEventFollow" collection
 * @method Doctrine_Collection getPosEventCheckin()       Returns the current record's "PosEventCheckin" collection
 * @method Doctrine_Collection getPosEventComment()       Returns the current record's "PosEventComment" collection
 * @method PosEvent            setId()                    Sets the current record's "id" value
 * @method PosEvent            setPosId()                 Sets the current record's "pos_id" value
 * @method PosEvent            setLat()                   Sets the current record's "lat" value
 * @method PosEvent            setLng()                   Sets the current record's "lng" value
 * @method PosEvent            setMemberId()              Sets the current record's "member_id" value
 * @method PosEvent            setPosEventCategoryId()    Sets the current record's "pos_event_category_id" value
 * @method PosEvent            setTitle()                 Sets the current record's "title" value
 * @method PosEvent            setDescription()           Sets the current record's "description" value
 * @method PosEvent            setWebsite()               Sets the current record's "website" value
 * @method PosEvent            setFileId()                Sets the current record's "file_id" value
 * @method PosEvent            setStartTime()             Sets the current record's "start_time" value
 * @method PosEvent            setEndTime()               Sets the current record's "end_time" value
 * @method PosEvent            setIsPublic()              Sets the current record's "is_public" value
 * @method PosEvent            setMeta()                  Sets the current record's "meta" value
 * @method PosEvent            setDelFlag()               Sets the current record's "del_flag" value
 * @method PosEvent            setRank()                  Sets the current record's "rank" value
 * @method PosEvent            setCreatedAt()             Sets the current record's "created_at" value
 * @method PosEvent            setUpdatedAt()             Sets the current record's "updated_at" value
 * @method PosEvent            setPos()                   Sets the current record's "Pos" value
 * @method PosEvent            setMember()                Sets the current record's "Member" value
 * @method PosEvent            setFile()                  Sets the current record's "File" value
 * @method PosEvent            setPosEventCategory()      Sets the current record's "PosEventCategory" value
 * @method PosEvent            setPosEventPhoto()         Sets the current record's "PosEventPhoto" collection
 * @method PosEvent            setPosEventFollow()        Sets the current record's "PosEventFollow" collection
 * @method PosEvent            setPosEventCheckin()       Sets the current record's "PosEventCheckin" collection
 * @method PosEvent            setPosEventComment()       Sets the current record's "PosEventComment" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosEvent extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_event');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies event',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             ));
        $this->hasColumn('pos_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id is of pos',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('lat', 'float', null, array(
             'type' => 'float',
             'comment' => 'latitude theo google map',
             'length' => '',
             ));
        $this->hasColumn('lng', 'float', null, array(
             'type' => 'float',
             'comment' => 'longitude theo google map',
             'length' => '',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id is member',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('pos_event_category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id is pos event category ',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'title is of event',
             'length' => 255,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'comment' => 'desc is of event',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'website of event',
             'length' => 255,
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'File id',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('start_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => 'Ngày bắt đầu sự kiện',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => 'Ngày kết thúc sự kiện',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('is_public', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '1',
             'comment' => '',
             'length' => 1,
             ));
        $this->hasColumn('meta', 'string', null, array(
             'type' => 'string',
             'comment' => 'Chứa các thông tin về title, description, address, tel, website của địa điểm',
             ));
        $this->hasColumn('del_flag', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'Xóa : = 1',
             'length' => 1,
             ));
        $this->hasColumn('rank', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'Xếp hạng sự kiện',
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pos', array(
             'local' => 'pos_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('PosEventCategory', array(
             'local' => 'pos_event_category_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('PosEventPhoto', array(
             'local' => 'id',
             'foreign' => 'pos_event_id'));

        $this->hasMany('PosEventFollow', array(
             'local' => 'id',
             'foreign' => 'pos_event_id'));

        $this->hasMany('PosEventCheckin', array(
             'local' => 'id',
             'foreign' => 'pos_event_id'));

        $this->hasMany('PosEventComment', array(
             'local' => 'id',
             'foreign' => 'pos_event_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}