<?php

/**
 * BasePosGoogleFlowContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $status
 * @property string $url
 * @property integer $area_id
 * @property integer $start
 * @property integer $flow_id
 * @property text $content
 * @property PosGoogleFlow $PosGoogleFlow
 * 
 * @method integer              getId()            Returns the current record's "id" value
 * @method integer              getStatus()        Returns the current record's "status" value
 * @method string               getUrl()           Returns the current record's "url" value
 * @method integer              getAreaId()        Returns the current record's "area_id" value
 * @method integer              getStart()         Returns the current record's "start" value
 * @method integer              getFlowId()        Returns the current record's "flow_id" value
 * @method text                 getContent()       Returns the current record's "content" value
 * @method PosGoogleFlow        getPosGoogleFlow() Returns the current record's "PosGoogleFlow" value
 * @method PosGoogleFlowContent setId()            Sets the current record's "id" value
 * @method PosGoogleFlowContent setStatus()        Sets the current record's "status" value
 * @method PosGoogleFlowContent setUrl()           Sets the current record's "url" value
 * @method PosGoogleFlowContent setAreaId()        Sets the current record's "area_id" value
 * @method PosGoogleFlowContent setStart()         Sets the current record's "start" value
 * @method PosGoogleFlowContent setFlowId()        Sets the current record's "flow_id" value
 * @method PosGoogleFlowContent setContent()       Sets the current record's "content" value
 * @method PosGoogleFlowContent setPosGoogleFlow() Sets the current record's "PosGoogleFlow" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosGoogleFlowContent extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_google_flow_content');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies pos',
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'trang thai of dia diem',
             'length' => 2,
             ));
        $this->hasColumn('url', 'string', 500, array(
             'type' => 'string',
             'comment' => 'url lay thong tin',
             'length' => 500,
             ));
        $this->hasColumn('area_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id identifies area',
             'length' => 4,
             ));
        $this->hasColumn('start', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'trang thai of dia diem',
             'length' => 4,
             ));
        $this->hasColumn('flow_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id identifies area',
             'length' => 4,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             'comment' => 'File url',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PosGoogleFlow', array(
             'local' => 'flow_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}