<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PosDeal', 'doctrine');

/**
 * BasePosDeal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pos_id
 * @property float $price
 * @property float $original_price
 * @property string $save
 * @property integer $num_buyers
 * @property string $link_news
 * @property string $source
 * @property timestamp $expire_date
 * @property integer $status
 * @property string $image_show
 * @property integer $sort_order
 * @property string $province
 * @property string $address
 * @property float $lat
 * @property float $lng
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Pos $Pos
 * 
 * @method integer   getId()             Returns the current record's "id" value
 * @method integer   getPosId()          Returns the current record's "pos_id" value
 * @method float     getPrice()          Returns the current record's "price" value
 * @method float     getOriginalPrice()  Returns the current record's "original_price" value
 * @method string    getSave()           Returns the current record's "save" value
 * @method integer   getNumBuyers()      Returns the current record's "num_buyers" value
 * @method string    getLinkNews()       Returns the current record's "link_news" value
 * @method string    getSource()         Returns the current record's "source" value
 * @method timestamp getExpireDate()     Returns the current record's "expire_date" value
 * @method integer   getStatus()         Returns the current record's "status" value
 * @method string    getImageShow()      Returns the current record's "image_show" value
 * @method integer   getSortOrder()      Returns the current record's "sort_order" value
 * @method string    getProvince()       Returns the current record's "province" value
 * @method string    getAddress()        Returns the current record's "address" value
 * @method float     getLat()            Returns the current record's "lat" value
 * @method float     getLng()            Returns the current record's "lng" value
 * @method timestamp getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()      Returns the current record's "updated_at" value
 * @method Pos       getPos()            Returns the current record's "Pos" value
 * @method PosDeal   setId()             Sets the current record's "id" value
 * @method PosDeal   setPosId()          Sets the current record's "pos_id" value
 * @method PosDeal   setPrice()          Sets the current record's "price" value
 * @method PosDeal   setOriginalPrice()  Sets the current record's "original_price" value
 * @method PosDeal   setSave()           Sets the current record's "save" value
 * @method PosDeal   setNumBuyers()      Sets the current record's "num_buyers" value
 * @method PosDeal   setLinkNews()       Sets the current record's "link_news" value
 * @method PosDeal   setSource()         Sets the current record's "source" value
 * @method PosDeal   setExpireDate()     Sets the current record's "expire_date" value
 * @method PosDeal   setStatus()         Sets the current record's "status" value
 * @method PosDeal   setImageShow()      Sets the current record's "image_show" value
 * @method PosDeal   setSortOrder()      Sets the current record's "sort_order" value
 * @method PosDeal   setProvince()       Sets the current record's "province" value
 * @method PosDeal   setAddress()        Sets the current record's "address" value
 * @method PosDeal   setLat()            Sets the current record's "lat" value
 * @method PosDeal   setLng()            Sets the current record's "lng" value
 * @method PosDeal   setCreatedAt()      Sets the current record's "created_at" value
 * @method PosDeal   setUpdatedAt()      Sets the current record's "updated_at" value
 * @method PosDeal   setPos()            Sets the current record's "Pos" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosDeal extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_deal');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies pos deal',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             ));
        $this->hasColumn('pos_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id identifies pos',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('price', 'float', 18, array(
             'type' => 'float',
             'comment' => 'Giá của sản phẩm',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('original_price', 'float', 18, array(
             'type' => 'float',
             'comment' => 'Giá gốc của sản phẩm',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('save', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Tiết kiệm sau khi mua chung',
             'length' => 10,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('num_buyers', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'Số lượng người mua',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('link_news', 'string', 200, array(
             'type' => 'string',
             'comment' => 'link tới trang chi tiết của sản phẩm',
             'length' => 200,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('source', 'string', 50, array(
             'type' => 'string',
             'comment' => 'id identifies category',
             'length' => 50,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('expire_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => 'ngày hết hạn mua chung',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'default' => '1',
             'comment' => 'còn bán => status = 1, hết hạn => status = 0, cháy hàng =>status = 2',
             'length' => 1,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('image_show', 'string', null, array(
             'type' => 'string',
             'comment' => 'Danh sách link ảnh của sản phẩm, mỗi link cách nhau bởi dấu một dấu ; ',
             'length' => '',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'default' => 1,
             'comment' => 'Thứ tự ưu tiên vị trí hiển thị của sản phẩm trên website',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('province', 'string', 100, array(
             'type' => 'string',
             'comment' => 'Tình thành',
             'length' => 100,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Địa chỉ cung cấp sản phẩm',
             'length' => 255,
             ));
        $this->hasColumn('lat', 'float', null, array(
             'type' => 'float',
             'comment' => 'latitude theo google map',
             'length' => '',
             ));
        $this->hasColumn('lng', 'float', null, array(
             'type' => 'float',
             'comment' => 'longitude theo google map',
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pos', array(
             'local' => 'pos_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}