<?php

/**
 * BasePosEventPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property integer $pos_event_id
 * @property integer $file_id
 * @property integer $claim_status
 * @property integer $status
 * @property integer $is_public
 * @property string $description
 * @property PosEvent $PosEvent
 * @property Member $Member
 * @property File $File
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getMemberId()     Returns the current record's "member_id" value
 * @method integer       getPosEventId()   Returns the current record's "pos_event_id" value
 * @method integer       getFileId()       Returns the current record's "file_id" value
 * @method integer       getClaimStatus()  Returns the current record's "claim_status" value
 * @method integer       getStatus()       Returns the current record's "status" value
 * @method integer       getIsPublic()     Returns the current record's "is_public" value
 * @method string        getDescription()  Returns the current record's "description" value
 * @method PosEvent      getPosEvent()     Returns the current record's "PosEvent" value
 * @method Member        getMember()       Returns the current record's "Member" value
 * @method File          getFile()         Returns the current record's "File" value
 * @method PosEventPhoto setId()           Sets the current record's "id" value
 * @method PosEventPhoto setMemberId()     Sets the current record's "member_id" value
 * @method PosEventPhoto setPosEventId()   Sets the current record's "pos_event_id" value
 * @method PosEventPhoto setFileId()       Sets the current record's "file_id" value
 * @method PosEventPhoto setClaimStatus()  Sets the current record's "claim_status" value
 * @method PosEventPhoto setStatus()       Sets the current record's "status" value
 * @method PosEventPhoto setIsPublic()     Sets the current record's "is_public" value
 * @method PosEventPhoto setDescription()  Sets the current record's "description" value
 * @method PosEventPhoto setPosEvent()     Sets the current record's "PosEvent" value
 * @method PosEventPhoto setMember()       Sets the current record's "Member" value
 * @method PosEventPhoto setFile()         Sets the current record's "File" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosEventPhoto extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_event_photo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies pos_photo',
             'length' => 4,
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id is of poster',
             'length' => 4,
             ));
        $this->hasColumn('pos_event_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => '',
             'length' => 4,
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'File id',
             'length' => 4,
             ));
        $this->hasColumn('claim_status', 'integer', 1, array(
             'type' => 'integer',
             'comment' => 'claim_status is of pos_photo',
             'length' => 1,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             'comment' => '',
             'length' => 1,
             ));
        $this->hasColumn('is_public', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '1',
             'comment' => '',
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'comment' => 'desc is of pos photo',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PosEvent', array(
             'local' => 'pos_event_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}