<?php

/**
 * BasePosGoogleFlow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $category
 * @property integer $status
 * @property string $keyword
 * @property string $url
 * @property string $area
 * @property integer $stop
 * @property integer $size_area
 * @property integer $max_content
 * @property integer $size_content
 * @property integer $timeout_content
 * @property integer $timeout_pos
 * @property Doctrine_Collection $PosGoogle
 * @property Doctrine_Collection $PosGoogleFlowContent
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getCategory()             Returns the current record's "category" value
 * @method integer             getStatus()               Returns the current record's "status" value
 * @method string              getKeyword()              Returns the current record's "keyword" value
 * @method string              getUrl()                  Returns the current record's "url" value
 * @method string              getArea()                 Returns the current record's "area" value
 * @method integer             getStop()                 Returns the current record's "stop" value
 * @method integer             getSizeArea()             Returns the current record's "size_area" value
 * @method integer             getMaxContent()           Returns the current record's "max_content" value
 * @method integer             getSizeContent()          Returns the current record's "size_content" value
 * @method integer             getTimeoutContent()       Returns the current record's "timeout_content" value
 * @method integer             getTimeoutPos()           Returns the current record's "timeout_pos" value
 * @method Doctrine_Collection getPosGoogle()            Returns the current record's "PosGoogle" collection
 * @method Doctrine_Collection getPosGoogleFlowContent() Returns the current record's "PosGoogleFlowContent" collection
 * @method PosGoogleFlow       setId()                   Sets the current record's "id" value
 * @method PosGoogleFlow       setCategory()             Sets the current record's "category" value
 * @method PosGoogleFlow       setStatus()               Sets the current record's "status" value
 * @method PosGoogleFlow       setKeyword()              Sets the current record's "keyword" value
 * @method PosGoogleFlow       setUrl()                  Sets the current record's "url" value
 * @method PosGoogleFlow       setArea()                 Sets the current record's "area" value
 * @method PosGoogleFlow       setStop()                 Sets the current record's "stop" value
 * @method PosGoogleFlow       setSizeArea()             Sets the current record's "size_area" value
 * @method PosGoogleFlow       setMaxContent()           Sets the current record's "max_content" value
 * @method PosGoogleFlow       setSizeContent()          Sets the current record's "size_content" value
 * @method PosGoogleFlow       setTimeoutContent()       Sets the current record's "timeout_content" value
 * @method PosGoogleFlow       setTimeoutPos()           Sets the current record's "timeout_pos" value
 * @method PosGoogleFlow       setPosGoogle()            Sets the current record's "PosGoogle" collection
 * @method PosGoogleFlow       setPosGoogleFlowContent() Sets the current record's "PosGoogleFlowContent" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosGoogleFlow extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_google_flow');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies pos',
             'length' => 4,
             ));
        $this->hasColumn('category', 'string', 255, array(
             'type' => 'string',
             'comment' => 'id identifies category',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'trang thai of dia diem',
             'length' => 2,
             ));
        $this->hasColumn('keyword', 'string', 50, array(
             'type' => 'string',
             'comment' => 'id identifies category',
             'length' => 50,
             ));
        $this->hasColumn('url', 'string', 500, array(
             'type' => 'string',
             'comment' => 'url lay thong tin',
             'length' => 500,
             ));
        $this->hasColumn('area', 'string', 50, array(
             'type' => 'string',
             'comment' => 'id identifies category',
             'length' => 50,
             ));
        $this->hasColumn('stop', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'trang thai of dia diem',
             'length' => 4,
             ));
        $this->hasColumn('size_area', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'So area quet 1 lan',
             'length' => 4,
             ));
        $this->hasColumn('max_content', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'so content lay tren 1 cell',
             'length' => 4,
             ));
        $this->hasColumn('size_content', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'So area quet 1 lan',
             'length' => 4,
             ));
        $this->hasColumn('timeout_content', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'So ms cho lan sau lay content',
             'length' => 4,
             ));
        $this->hasColumn('timeout_pos', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'So ms cho lan sau lay pos',
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PosGoogle', array(
             'local' => 'id',
             'foreign' => 'flow_id'));

        $this->hasMany('PosGoogleFlowContent', array(
             'local' => 'id',
             'foreign' => 'flow_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}