<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PosEventCategory', 'doctrine');

/**
 * BasePosEventCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $file_id
 * @property integer $sort_order
 * @property string $code
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property File $File
 * @property Doctrine_Collection $PosEvent
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getFileId()      Returns the current record's "file_id" value
 * @method integer             getSortOrder()   Returns the current record's "sort_order" value
 * @method string              getCode()        Returns the current record's "code" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method File                getFile()        Returns the current record's "File" value
 * @method Doctrine_Collection getPosEvent()    Returns the current record's "PosEvent" collection
 * @method PosEventCategory    setId()          Sets the current record's "id" value
 * @method PosEventCategory    setName()        Sets the current record's "name" value
 * @method PosEventCategory    setDescription() Sets the current record's "description" value
 * @method PosEventCategory    setFileId()      Sets the current record's "file_id" value
 * @method PosEventCategory    setSortOrder()   Sets the current record's "sort_order" value
 * @method PosEventCategory    setCode()        Sets the current record's "code" value
 * @method PosEventCategory    setCreatedAt()   Sets the current record's "created_at" value
 * @method PosEventCategory    setUpdatedAt()   Sets the current record's "updated_at" value
 * @method PosEventCategory    setFile()        Sets the current record's "File" value
 * @method PosEventCategory    setPosEvent()    Sets the current record's "PosEvent" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosEventCategory extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pos_event_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'id identifies event category',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'name of event category',
             'length' => 100,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'des of event category ',
             'length' => '',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'File id',
             'length' => 4,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('sort_order', 'integer', 1, array(
             'type' => 'integer',
             'default' => '10',
             'comment' => '',
             'length' => 1,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('code', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'comment' => 'code of pos event category',
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', '');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('PosEvent', array(
             'local' => 'id',
             'foreign' => 'pos_event_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}