<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2012/03/28 02:21:17
return array (
  'gadget' => 
  array (
    'name' => 'ホーム画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'homeGadgetPlot',
    ),
  ),
  'profile' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'profileGadgetPlot',
    ),
  ),
  'memberAction' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'memberActionGadgetPlot',
    ),
  ),
  'pos' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'posGadgetPlot',
    ),
  ),
  'posRentHouse' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'posRentHouseGadgetPlot',
    ),
  ),
  'posEvent' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'posEventGadgetPlot',
    ),
  ),
  'community' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'communityGadgetPlot',
    ),
  ),
  'login' => 
  array (
    'name' => 'ログイン画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'loginGadgetPlot',
    ),
  ),
  'sideBanner' => 
  array (
    'name' => 'サイドバナー',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'sideBannerGadgetPlot',
    ),
  ),
  'mobile' => 
  array (
    'name' => '携帯版ホーム画面',
    'layout' => 
    array (
      'default' => 'layoutE',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileHomeGadgetPlot',
    ),
  ),
  'mobileProfile' => 
  array (
    'name' => '携帯版プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutE',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileProfileGadgetPlot',
    ),
  ),
  'mobileLogin' => 
  array (
    'name' => '携帯版ログイン画面',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileLoginGadgetPlot',
    ),
  ),
  'mobileHeader' => 
  array (
    'name' => '携帯版ヘッダー',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileHeaderGadgetPlot',
    ),
  ),
  'mobileFooter' => 
  array (
    'name' => '携帯版フッター',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileFooterGadgetPlot',
    ),
  ),
  'dailyNews' => 
  array (
    'name' => 'デイリーニュース（PCメールアドレス向け）',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'dailyNewsGadgetPlot',
    ),
  ),
  'mobileDailyNews' => 
  array (
    'name' => 'デイリーニュース（携帯メールアドレス向け）',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileDailyNewsGadgetPlot',
    ),
  ),
  'dashboardPos' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'dashboardPosGadgetPlot',
    ),
  ),
  'dashboardRentHouse' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'dashboardRentHouseGadgetPlot',
    ),
  ),
  'dashboardMain' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'dashboardMainGadgetPlot',
    ),
  ),
  'dashboardMember' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'dashboardMemberGadgetPlot',
    ),
  ),
  'searchallBytext' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'searchallBytextGadgetPlot',
    ),
  ),
);
