<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2012/03/28 02:21:17
return array (
  'layoutA' => 
  array (
    0 => 'top',
    1 => 'sideMenu',
    2 => 'contents',
    3 => 'bottom',
    4 => 'sideRightMenu',
    5 => 'configMember',
  ),
  'layoutB' => 
  array (
    0 => 'sideMenu',
    1 => 'sideRightMenu',
    2 => 'contents',
    3 => 'bottom',
  ),
  'layoutC' => 
  array (
    0 => 'contents',
    1 => 'bottom',
  ),
  'layoutD' => 
  array (
    0 => 'contents',
  ),
  'layoutE' => 
  array (
    0 => 'top',
    1 => 'contents',
    2 => 'bottom',
  ),
);
