<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/03/28 02:21:10
sfConfig::add(array(
  'app_update_span_minute' => 5,
  'app_blog_action_size' => 20,
  'app_blog_component_size' => 5,
  'app_update_blog_rss_cache_limit' => 100,
  'app_blog_rss_cache_dir' => '/plugins/opBlogPlugin',
  'app_max_introfriend' => 5,
  'app_line_introfriend' => 5,
  'app_ranking_display_self_introduction' => false,
  'app_diary_is_upload_images' => true,
  'app_diary_max_image_file_num' => 3,
  'app_diary_comment_is_upload_images' => true,
  'app_diary_comment_max_image_file_num' => 3,
  'app_message_is_upload_images' => true,
  'app_message_max_image_file_num' => 3,
  'app_message_pagenate_size' => 20,
));
