<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2012/03/29 02:14:58
return array (
  'provinces' => 
  array (
    'hanoi' => 
    array (
      'name' => 'Hà Nội',
      'code' => 'hanoi',
      'latlng' => '21.01112433754,105.83893784119',
    ),
    'hochiminh' => 
    array (
      'name' => 'Hồ Chí Minh',
      'code' => 'hochiminh',
      'latlng' => '10.8019599999,106.7117279999',
    ),
    'danang' => 
    array (
      'name' => 'Đà Nẵng',
      'code' => 'danang',
      'latlng' => '16.058237999999999,108.212639',
    ),
    'haiphong' => 
    array (
      'name' => 'Hải Phòng',
      'code' => 'haiphong',
      'latlng' => '20.849999999999998,106.6833333',
    ),
  ),
  'sources' => 
  array (
    'muachung.vn' => 
    array (
      'name' => 'muachung.vn',
      'website' => 'muachung.vn',
      'provinces' => 'hanoi,hochiminh,danang,haiphong',
      'addresses' => '27 Mai Hắc Đế, Hai Bà Trưng, Hà Nội',
    ),
    'vndoan.com' => 
    array (
      'name' => 'vndoan.com',
      'website' => 'vndoan.com',
      'provinces' => 'hanoi,hochiminh',
      'addresses' => 'Phòng 1007 Nhà 17T6 Khu Đô Thị Trung Hòa Nhân Chính, Phường Nhân Chính,  Quận Thanh Xuân, Hà Nội',
    ),
    'nhommua.com' => 
    array (
      'name' => 'nhommua.com',
      'website' => 'nhommua.com',
      'provinces' => 'hanoi,hochiminh',
      'addresses' => 'Tòa nhà Vincom, Tầng 14,72 Lê Thánh Tôn,P.Bến Nghé, Q.1, HCMC',
    ),
  ),
  'statuses' => 
  array (
    1 => 'Còn bán',
    0 => 'Hết hạn',
    2 => 'Cháy hàng',
  ),
  'orderes' => 
  array (
    1 => 'Bình thường',
    5 => 'Mức 5',
    10 => 'Mức 10',
    15 => 'Mức 15',
    20 => 'Mức 20',
  ),
);
