<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/28 02:21:14

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=lifemap_new;host=localhost;port=3306',
  'username' => 'root',
  'encoding' => 'utf8',
  'attributes' => 
  array (
    164 => true,
  ),
  'name' => 'doctrine',
)),);
