<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/03/29 04:56:46
sfConfig::add(array(
  'mod_friend_enabled' => true,
  'mod_friend_view_class' => 'op',
  'mod_friend_default_nav' => 'friend',
));
