<?php
// auto-generated by sfCacheConfigHandler
// date: 2012/03/28 02:21:21
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

