<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2012/03/28 02:21:16
return array (
  'enable_mobile' => 
  array (
    'IsConfig' => false,
    'Default' => 0,
  ),
  'enable_pc' => 
  array (
    'Default' => 0,
  ),
  'admin_invite' => 
  array (
    'Default' => false,
  ),
);
