<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2012/03/28 02:21:15
return array (
  'invite_mode' => 
  array (
    'Default' => 2,
  ),
  'enable_mobile' => 
  array (
    'Default' => 1,
  ),
  'enable_pc' => 
  array (
    'Default' => 1,
  ),
  'self_invite_action' => 
  array (
    'Default' => 'opAuthMailAddress/requestRegisterURL',
  ),
  'help_login_error_action' => 
  array (
    'Name' => 'self_invite_action',
    'Caption' => '',
    'FormType' => '',
    'ValueType' => '',
    'IsConfig' => false,
    'IsRequired' => false,
    'Default' => 'opAuthMailAddress/passwordRecovery',
  ),
  'is_check_multiple_address' => 
  array (
    'Name' => 'is_check_multiple_address',
    'Caption' => 'Đăng nhập thiết lập địa chỉ email',
    'FormType' => 'radio',
    'ValueType' => 'text',
    'IsConfig' => true,
    'IsRequired' => true,
    'Default' => 0,
    'Choices' => 
    array (
      1 => 'Chấp nhận đăng nhập bằng e-mail PC và e-mail di động',
      0 => 'Chấp nhận đăng nhập chỉ bằng e-mail PC hoặc e-mail di động',
    ),
  ),
  'auth_mode_caption' => 
  array (
    'IsConfig' => 0,
    'Default' => 'E-mail Address Login',
  ),
);
