<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2012/03/28 02:21:15
return array (
  'invite_mode' => 
  array (
    'Name' => 'invite_mode',
    'Caption' => '招待モード',
    'FormType' => 'radio',
    'ValueType' => 'text',
    'IsConfig' => true,
    'IsRequired' => true,
    'Default' => 2,
    'Choices' => 
    array (
      2 => '招待なしでの登録を許可する',
      1 => 'SNS参加者に招待を許可する',
      0 => '招待を許可しない',
    ),
  ),
  'enable_pc' => 
  array (
    'Name' => 'enable_pc',
    'Caption' => 'PC版有効設定',
    'FormType' => 'radio',
    'ValueType' => 'text',
    'IsConfig' => true,
    'IsRequired' => true,
    'Default' => 1,
    'Choices' => 
    array (
      0 => '無効にする',
      1 => '有効にする',
    ),
  ),
  'enable_mobile' => 
  array (
    'Name' => 'enable_mobile',
    'Caption' => '携帯版有効設定',
    'FormType' => 'radio',
    'ValueType' => 'text',
    'IsConfig' => true,
    'IsRequired' => true,
    'Default' => 1,
    'Choices' => 
    array (
      0 => '無効にする',
      1 => '有効にする',
    ),
  ),
  'self_invite_action' => 
  array (
    'IsConfig' => false,
    'Default' => true,
  ),
  'admin_invite' => 
  array (
    'IsConfig' => false,
    'Default' => true,
  ),
);
