<?php

/**
 * BaseSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $session_data
 * @property string $time
 * 
 * @method string  getId()           Returns the current record's "id" value
 * @method string  getSessionData()  Returns the current record's "session_data" value
 * @method string  getTime()         Returns the current record's "time" value
 * @method Session setId()           Sets the current record's "id" value
 * @method Session setSessionData()  Sets the current record's "session_data" value
 * @method Session setTime()         Sets the current record's "time" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSession extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('session');
        $this->hasColumn('id', 'string', 128, array(
             'type' => 'string',
             'primary' => true,
             'length' => 128,
             ));
        $this->hasColumn('session_data', 'string', null, array(
             'type' => 'string',
             'comment' => 'Session information',
             ));
        $this->hasColumn('time', 'string', null, array(
             'type' => 'string',
             'comment' => 'Timestamp of generated time',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves session data');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}