<?php

/**
 * PluginPosRentHouseCrawlSourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPosRentHouseCrawlSourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPosRentHouseCrawlSourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPosRentHouseCrawlSource');
    }
    public function getListRentHouseSource($page = 1, $size = 10){
        $q = $this->createQuery('p');
        return $this->getPager($q, $page, $size);
    }
    protected function getPager(Doctrine_Query $q, $page, $size) {
        $pager = new sfDoctrinePager('PosRentHouseCrawlSource', $size);
        $pager->setQuery($q);
        $pager->setPage($page);
        return $pager;
    }
}