<?php

/**
 * PluginPosPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPosPhotoTable extends Doctrine_Table
{
    const is_active = 1;
    const is_public = 1;
    const is_show = 1;
    const numOfPosShow = 16;
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPosPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPosPhoto');
    }
     /*Nguyen Hue 07/11/2011 */
    public function getImagesPosList($posId)
    {
      $q = $this->createQuery()
        ->where('pos_id = ?', $posId)
        ->andWhere('status = ?', self::is_active)
        ->andWhere('is_public =?',self::is_public)
        ->orderBy('created_at DESC')
        ->limit(10);
      return $q->execute();
    }
    public function getAllImagesPos($posId){
      $q = $this->createQuery()
        ->where('pos_id = ?', $posId)
        ->andWhere('status = ?', self::is_active)
        ->andWhere('is_public =?',self::is_public)
        ->orderBy('created_at DESC');
      return $q->execute();
    }
    public function getImagesPosListAll($posId)
    {
      $q = $this->createQuery()
        ->where('pos_id = ?', $posId)
        ->andWhere('status = ?', 1)
        ->orderBy('created_at DESC');
      return $q->execute();
    }
    public function searchImage($fileId,$posId){
      $q = $this->createQuery()
          ->where('file_id =?', $fileId)
          ->andWhere('pos_id =?',$posId);
      return $q->execute();
    }
    public function save($memberId,$posId,$fileId,$status,$isPublic,$desc = null){
        $pos = Doctrine::getTable('Pos')->find($posId);
        $posPhoto = new PosPhoto();
        $posPhoto->member_id = $memberId;
        $posPhoto->pos_id = $posId;
        $posPhoto->file_id = $fileId;
        $posPhoto->status = $status;
        $posPhoto->is_public = $isPublic;
        $posPhoto->pos_category_id = $pos->getPosCategoryId();
        if($desc) $posPhoto->description = $desc;
        $posPhoto->save();
        return $posPhoto;
    }
    /*
     * huent
     * xóa ảnh
     */
    public function deletePosPhoto($id){
        return $this->createQuery()
            ->delete()
            ->where('id = ?',$id)
            ->execute();
    }
    /* Danh sách hình ảnh mới cho địa điểm */
    public function getNewPhotoPosList($num){
      if($num)
          return $q = $this->createQuery('pp')
              ->innerJoin('pp.PosCategory pcr')
              ->where('pp.status =?',self::is_active)
              ->andWhere('pp.is_public =?',self::is_public)
              ->andWhere('pcr.type =?',self::is_show)
              ->orderBy('created_at DESC')
              ->limit($num)
              ->execute();
   }
   /* Danh sách hình ảnh mới cho nhà cho thuê */
    public function getNewPhotoRentHouseList($num){
      $posCategory = Doctrine::getTable('PosCategory')->getCategoryFromCode(PluginPosCategoryTable::rent_house_code);
      if($num)
          return $q = $this->createQuery()
              ->where('status =?',self::is_active)
              ->andWhere('is_public =?',self::is_public)
              ->andWhere('pos_category_id =?',$posCategory->getId())
              ->orderBy('created_at DESC')
              ->limit($num)
              ->execute();
   }
   protected function getPager(Doctrine_Query $q, $page, $size)
    {
      $pager = new sfDoctrinePager('PosPhoto', $size);
      $pager->setQuery($q);
      $pager->setPage($page);
      $pager->init();
      return $pager;
    }
   /* pager danh sách ảnh của địa điểm*/
   public function getNewPhotoPosListPager($page = 1,$size = 12){
            $q = $this->createQuery('pp')
              ->innerJoin('pp.PosCategory pcr')
              ->where('pp.status =?',self::is_active)
              ->andWhere('pp.is_public =?',self::is_public)
              ->andWhere('pcr.type =?',self::is_show)
              ->orderBy('created_at DESC');
           return $this->getPager($q,$page,$size);
   }
   /* pager danh sách hình ảnh mới cho nhà cho thuê */
    public function getNewPhotoRentHouseListPager($page = 1,$size = 12){
          $posCategory = Doctrine::getTable('PosCategory')->getCategoryFromCode(PluginPosCategoryTable::rent_house_code);
          $q = $this->createQuery()
              ->where('status =?',self::is_active)
              ->andWhere('is_public =?',self::is_public)
              ->andWhere('pos_category_id =?',$posCategory->getId())
              ->orderBy('created_at DESC');
          return $this->getPager($q,$page,$size);
    }
}