<?php

/**
 * PluginPosEventCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPosEventCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPosEventCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPosEventCategory');
    }
    
    public function getEventCategoryById($id) {
        $q = $this->createQuery('ec')
                ->select('ec.name')
                ->where('ec.id = ?', $id);
        $ec = $q->fetchOne();
        return $ec->getName();
    }
    
    public function getCodeById($id) {
        $q = $this->createQuery()
                ->select('code')
                ->where('id=?', $id);
        return $q->fetchOne()->getCode();
    }
}