<?php

/**
 * PluginPosRentHouse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPosRentHouse extends BasePosRentHouse
{
    const ranges_0 = 0;
    const ranges_1 = 1;
    const const_ranges_1 = 1;
    const ranges_2 = 3;
    const const_ranges_2 = 2;
    const ranges_3 = 5;
    const const_ranges_3 = 3;
    const ranges_4 = 10;
    const const_ranges_4 = 4;
    const const_ranges_5 = 5;
    public function getConstRanges($priceStr){
        $price = (int)$priceStr;
        $ranges = null;
        switch ($price)
        {
          case ($price >= self::ranges_0 && $price < self::ranges_1):
              $ranges = self::const_ranges_1;
              break;
          case ($price >= self::ranges_1 && $price < self::ranges_2):
              $ranges = self::const_ranges_2;
              break;
          case ($price >= self::ranges_2 && $price < self::ranges_3):
              $ranges = self::const_ranges_3;
              break;
          case ($price >= self::ranges_3 && $price < self::ranges_4):
              $ranges = self::const_ranges_4;
              break;
          case ($price >= self::ranges_4):
              $ranges = self::const_ranges_5;
              break;
        }
        return $ranges;
    }
}