<?php

/**
 * PluginPosWarnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPosWarnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPosWarnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPosWarn');
    }
}