<?php

/**
 * PluginPosEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPosEvent extends BasePosEvent
{
    public function getSubDescription($length = null){
        if(!isset($length)) $length = 300;
        if(strlen(utf8_decode($this->getDescription()))>$length){
          $space = strrpos($this->getDescription(), " ", -(strlen($this->getDescription()) - $length));
          $str = substr($this->getDescription(),0,$space).'...';
          return $str;
        }else{
          return $this->getDescription();
        }
    }
}