<?php

/**
 * PluginPosRentHouseCrawlPosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPosRentHouseCrawlPosTable extends Doctrine_Table
{
    const init = 0;
    const update = 1;
    const process = 2;
    const finish = 3;
    const delete = 4;
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPosRentHouseCrawlPosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPosRentHouseCrawlPos');
    }
    /**
     * Kiem tra trung cid
     *
     * @thuclh
     */
    public function checkCid($cid){
        $q = $this->createQuery('p')
            ->where('cid = ?',$cid);
        return $q->count()?true:false;
    }
    public function getRentHousePosByIdAndStatus($id,$status=1){
        $q = $this->createQuery('p')
        ->where('status = ?', $status)
        ->andWhere('id = ?',$id);
        return $q->fetchOne();
    }

    public function getListRentHousePos($id,$limit=300){
        $q = $this->createQuery('p')
        ->where('status = ?', self::init)
        ->andWhere('source_id = ?',$id)
        ->limit($limit);
        return $q->execute();
    }
    public function getListRentHousePosPager($status,$page = 1, $size = 10){
        $q = $this->createQuery('p')
        ->where('status = ?', $status)
        ->orderBy('id desc');
        return $this->getPager($q, $page, $size);
    }
    protected function getPager(Doctrine_Query $q, $page, $size) {
        $pager = new sfDoctrinePager('PosRentHouseCrawlPos', $size);
        $pager->setQuery($q);
        $pager->setPage($page);
        return $pager;
    }
}